@startuml
abstract class org.josemalucero.dominio.operacion.Operacion
annotation java.lang.Override
class java.io.IOException
class java.math.BigDecimal
class java.math.RoundingMode
class java.time.LocalDateTime
class java.util.ArrayList
class java.util.Arrays
class java.util.Optional
class java.util.Random
class java.util.Scanner
class org.josemalucero.app.AlkeWallet
class org.josemalucero.app.Main
class org.josemalucero.dominio.cuenta.Cuenta
class org.josemalucero.dominio.cuenta.CuentaRegular
class org.josemalucero.dominio.estados.EstadoConversionMonedas
class org.josemalucero.dominio.estados.EstadoCreacionCuenta
class org.josemalucero.dominio.estados.EstadoEntrada
class org.josemalucero.dominio.estados.EstadoLogin
class org.josemalucero.dominio.estados.EstadoOperaciones
class org.josemalucero.dominio.estados.EstadoSalir
class org.josemalucero.dominio.estados.EstadoSignIn
class org.josemalucero.dominio.moneda.ConversorMoneda
class org.josemalucero.dominio.moneda.Moneda
class org.josemalucero.dominio.moneda.MonedaConvertible
class org.josemalucero.dominio.operacion.OperacionConsulta
class org.josemalucero.dominio.operacion.OperacionDeMonto
class org.josemalucero.dominio.operacion.OperacionDeposito
class org.josemalucero.dominio.operacion.OperacionRetiro
class org.josemalucero.dominio.operacion.OperacionTransferencia
class org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaDestino
class org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaOrigen
class org.josemalucero.dominio.operacion.RegistroOperacion
class org.josemalucero.dominio.usuario.ContextoUsuario
class org.josemalucero.dominio.usuario.Usuario
class org.josemalucero.servicio.BCryptPasswordEncoderService
class org.josemalucero.servicio.ConsoleInputProvider
class org.josemalucero.servicio.FormateadorDeRegistroAImprimir
class org.josemalucero.servicio.RepositorioMonedas
class org.josemalucero.servicio.RepositorioUsuarios
class org.josemalucero.servicio.RespositorioCuentas
class org.mindrot.jbcrypt.BCrypt
enum org.josemalucero.dominio.operacion.EstadoOperacion
interface org.josemalucero.dominio.cuenta.Consultable
interface org.josemalucero.dominio.cuenta.Depositable
interface org.josemalucero.dominio.cuenta.Retirable
interface org.josemalucero.dominio.cuenta.Transferible
interface org.josemalucero.dominio.estados.EstadoUsuario
interface org.josemalucero.dominio.operacion.Registrable
interface org.josemalucero.dominio.operacion.Reversible
interface org.josemalucero.dominio.operacion.Validable
interface org.josemalucero.servicio.InputProvider
interface org.josemalucero.servicio.PasswordEncoder
org.josemalucero.dominio.operacion.Operacion ..> java.math.BigDecimal
org.josemalucero.dominio.operacion.Operacion ..> org.josemalucero.dominio.cuenta.CuentaRegular
org.josemalucero.app.AlkeWallet ..> org.josemalucero.dominio.usuario.ContextoUsuario
org.josemalucero.app.AlkeWallet ..> org.josemalucero.servicio.BCryptPasswordEncoderService
org.josemalucero.app.AlkeWallet ..> org.josemalucero.servicio.RepositorioMonedas
org.josemalucero.app.AlkeWallet ..> org.josemalucero.servicio.RepositorioUsuarios
org.josemalucero.app.Main ..> java.io.IOException
org.josemalucero.app.Main ..> org.josemalucero.dominio.usuario.ContextoUsuario
org.josemalucero.app.Main ..> org.josemalucero.servicio.ConsoleInputProvider
org.josemalucero.dominio.cuenta.Cuenta ..> java.util.ArrayList
org.josemalucero.dominio.cuenta.Cuenta ..> org.josemalucero.dominio.moneda.Moneda
org.josemalucero.dominio.cuenta.Cuenta ..> org.josemalucero.dominio.moneda.MonedaConvertible
org.josemalucero.dominio.cuenta.Cuenta ..> org.josemalucero.dominio.operacion.RegistroOperacion
org.josemalucero.dominio.cuenta.CuentaRegular ..> java.lang.Override
org.josemalucero.dominio.cuenta.CuentaRegular ..> java.math.BigDecimal
org.josemalucero.dominio.cuenta.CuentaRegular --|> org.josemalucero.dominio.cuenta.Cuenta
org.josemalucero.dominio.cuenta.CuentaRegular --|> org.josemalucero.dominio.cuenta.Consultable
org.josemalucero.dominio.cuenta.CuentaRegular --|> org.josemalucero.dominio.cuenta.Depositable
org.josemalucero.dominio.cuenta.CuentaRegular --|> org.josemalucero.dominio.cuenta.Retirable
org.josemalucero.dominio.cuenta.CuentaRegular --|> org.josemalucero.dominio.cuenta.Transferible
org.josemalucero.dominio.estados.EstadoConversionMonedas ..> java.lang.Override
org.josemalucero.dominio.estados.EstadoConversionMonedas ..> java.math.BigDecimal
org.josemalucero.dominio.estados.EstadoConversionMonedas ..> java.util.Optional
org.josemalucero.dominio.estados.EstadoConversionMonedas ..> org.josemalucero.dominio.moneda.ConversorMoneda
org.josemalucero.dominio.estados.EstadoConversionMonedas ..> org.josemalucero.dominio.moneda.MonedaConvertible
org.josemalucero.dominio.estados.EstadoConversionMonedas ..> org.josemalucero.dominio.usuario.ContextoUsuario
org.josemalucero.dominio.estados.EstadoConversionMonedas ..> org.josemalucero.servicio.RepositorioMonedas
org.josemalucero.dominio.estados.EstadoConversionMonedas --|> org.josemalucero.dominio.estados.EstadoUsuario
org.josemalucero.dominio.estados.EstadoConversionMonedas ..> org.josemalucero.servicio.InputProvider
org.josemalucero.dominio.estados.EstadoCreacionCuenta ..> java.lang.Override
org.josemalucero.dominio.estados.EstadoCreacionCuenta ..> java.math.BigDecimal
org.josemalucero.dominio.estados.EstadoCreacionCuenta ..> org.josemalucero.dominio.cuenta.CuentaRegular
org.josemalucero.dominio.estados.EstadoCreacionCuenta ..> org.josemalucero.dominio.operacion.RegistroOperacion
org.josemalucero.dominio.estados.EstadoCreacionCuenta ..> org.josemalucero.dominio.usuario.ContextoUsuario
org.josemalucero.dominio.estados.EstadoCreacionCuenta ..> org.josemalucero.servicio.RepositorioMonedas
org.josemalucero.dominio.estados.EstadoCreacionCuenta --|> org.josemalucero.dominio.estados.EstadoUsuario
org.josemalucero.dominio.estados.EstadoCreacionCuenta --|> org.josemalucero.dominio.operacion.Registrable
org.josemalucero.dominio.estados.EstadoEntrada ..> java.lang.Override
org.josemalucero.dominio.estados.EstadoEntrada ..> org.josemalucero.dominio.usuario.ContextoUsuario
org.josemalucero.dominio.estados.EstadoEntrada ..> org.josemalucero.dominio.usuario.Usuario
org.josemalucero.dominio.estados.EstadoEntrada --|> org.josemalucero.dominio.estados.EstadoUsuario
org.josemalucero.dominio.estados.EstadoLogin ..> java.lang.Override
org.josemalucero.dominio.estados.EstadoLogin ..> java.util.Optional
org.josemalucero.dominio.estados.EstadoLogin ..> org.josemalucero.dominio.usuario.ContextoUsuario
org.josemalucero.dominio.estados.EstadoLogin ..> org.josemalucero.dominio.usuario.Usuario
org.josemalucero.dominio.estados.EstadoLogin ..> org.josemalucero.servicio.BCryptPasswordEncoderService
org.josemalucero.dominio.estados.EstadoLogin ..> org.josemalucero.servicio.RepositorioUsuarios
org.josemalucero.dominio.estados.EstadoLogin --|> org.josemalucero.dominio.estados.EstadoUsuario
org.josemalucero.dominio.estados.EstadoLogin ..> org.josemalucero.servicio.InputProvider
org.josemalucero.dominio.estados.EstadoOperaciones ..> java.lang.Override
org.josemalucero.dominio.estados.EstadoOperaciones ..> java.math.BigDecimal
org.josemalucero.dominio.estados.EstadoOperaciones ..> java.util.ArrayList
org.josemalucero.dominio.estados.EstadoOperaciones ..> java.util.Optional
org.josemalucero.dominio.estados.EstadoOperaciones ..> org.josemalucero.dominio.cuenta.CuentaRegular
org.josemalucero.dominio.estados.EstadoOperaciones ..> org.josemalucero.dominio.moneda.ConversorMoneda
org.josemalucero.dominio.estados.EstadoOperaciones ..> org.josemalucero.dominio.usuario.ContextoUsuario
org.josemalucero.dominio.estados.EstadoOperaciones ..> org.josemalucero.dominio.usuario.Usuario
org.josemalucero.dominio.estados.EstadoOperaciones ..> org.josemalucero.servicio.FormateadorDeRegistroAImprimir
org.josemalucero.dominio.estados.EstadoOperaciones ..> org.josemalucero.servicio.RepositorioUsuarios
org.josemalucero.dominio.estados.EstadoOperaciones ..> org.josemalucero.dominio.cuenta.Transferible
org.josemalucero.dominio.estados.EstadoOperaciones --|> org.josemalucero.dominio.estados.EstadoUsuario
org.josemalucero.dominio.estados.EstadoOperaciones ..> org.josemalucero.servicio.InputProvider
org.josemalucero.dominio.estados.EstadoSalir ..> java.lang.Override
org.josemalucero.dominio.estados.EstadoSalir ..> org.josemalucero.dominio.usuario.ContextoUsuario
org.josemalucero.dominio.estados.EstadoSalir --|> org.josemalucero.dominio.estados.EstadoUsuario
org.josemalucero.dominio.estados.EstadoSignIn ..> java.lang.Override
org.josemalucero.dominio.estados.EstadoSignIn ..> java.util.Optional
org.josemalucero.dominio.estados.EstadoSignIn ..> org.josemalucero.dominio.usuario.ContextoUsuario
org.josemalucero.dominio.estados.EstadoSignIn ..> org.josemalucero.dominio.usuario.Usuario
org.josemalucero.dominio.estados.EstadoSignIn ..> org.josemalucero.servicio.BCryptPasswordEncoderService
org.josemalucero.dominio.estados.EstadoSignIn ..> org.josemalucero.servicio.RepositorioUsuarios
org.josemalucero.dominio.estados.EstadoSignIn --|> org.josemalucero.dominio.estados.EstadoUsuario
org.josemalucero.dominio.estados.EstadoSignIn ..> org.josemalucero.servicio.InputProvider
org.josemalucero.dominio.moneda.ConversorMoneda ..> java.math.BigDecimal
org.josemalucero.dominio.moneda.ConversorMoneda ..> java.math.RoundingMode
org.josemalucero.dominio.moneda.MonedaConvertible ..> java.math.BigDecimal
org.josemalucero.dominio.moneda.MonedaConvertible --|> org.josemalucero.dominio.moneda.Moneda
org.josemalucero.dominio.operacion.OperacionConsulta --|> org.josemalucero.dominio.operacion.Operacion
org.josemalucero.dominio.operacion.OperacionConsulta ..> java.lang.Override
org.josemalucero.dominio.operacion.OperacionConsulta ..> java.math.BigDecimal
org.josemalucero.dominio.operacion.OperacionConsulta ..> org.josemalucero.dominio.cuenta.CuentaRegular
org.josemalucero.dominio.operacion.OperacionDeMonto --|> org.josemalucero.dominio.operacion.Operacion
org.josemalucero.dominio.operacion.OperacionDeMonto ..> java.lang.Override
org.josemalucero.dominio.operacion.OperacionDeMonto ..> java.math.BigDecimal
org.josemalucero.dominio.operacion.OperacionDeMonto ..> org.josemalucero.dominio.cuenta.CuentaRegular
org.josemalucero.dominio.operacion.OperacionDeposito ..> java.lang.Override
org.josemalucero.dominio.operacion.OperacionDeposito ..> java.math.BigDecimal
org.josemalucero.dominio.operacion.OperacionDeposito ..> org.josemalucero.dominio.cuenta.CuentaRegular
org.josemalucero.dominio.operacion.OperacionDeposito --|> org.josemalucero.dominio.operacion.OperacionDeMonto
org.josemalucero.dominio.operacion.OperacionDeposito --|> org.josemalucero.dominio.operacion.Registrable
org.josemalucero.dominio.operacion.OperacionDeposito --|> org.josemalucero.dominio.operacion.Reversible
org.josemalucero.dominio.operacion.OperacionDeposito --|> org.josemalucero.dominio.operacion.Validable
org.josemalucero.dominio.operacion.OperacionRetiro ..> java.lang.Override
org.josemalucero.dominio.operacion.OperacionRetiro ..> java.math.BigDecimal
org.josemalucero.dominio.operacion.OperacionRetiro ..> java.time.LocalDateTime
org.josemalucero.dominio.operacion.OperacionRetiro ..> org.josemalucero.dominio.cuenta.Cuenta
org.josemalucero.dominio.operacion.OperacionRetiro ..> org.josemalucero.dominio.cuenta.CuentaRegular
org.josemalucero.dominio.operacion.OperacionRetiro --|> org.josemalucero.dominio.operacion.OperacionDeMonto
org.josemalucero.dominio.operacion.OperacionRetiro --|> org.josemalucero.dominio.operacion.Registrable
org.josemalucero.dominio.operacion.OperacionRetiro --|> org.josemalucero.dominio.operacion.Reversible
org.josemalucero.dominio.operacion.OperacionRetiro --|> org.josemalucero.dominio.operacion.Validable
org.josemalucero.dominio.operacion.OperacionTransferencia ..> java.lang.Override
org.josemalucero.dominio.operacion.OperacionTransferencia ..> java.math.BigDecimal
org.josemalucero.dominio.operacion.OperacionTransferencia ..> java.time.LocalDateTime
org.josemalucero.dominio.operacion.OperacionTransferencia ..> org.josemalucero.dominio.cuenta.Cuenta
org.josemalucero.dominio.operacion.OperacionTransferencia ..> org.josemalucero.dominio.cuenta.CuentaRegular
org.josemalucero.dominio.operacion.OperacionTransferencia --|> org.josemalucero.dominio.operacion.OperacionDeMonto
org.josemalucero.dominio.operacion.OperacionTransferencia ..> org.josemalucero.dominio.cuenta.Consultable
org.josemalucero.dominio.operacion.OperacionTransferencia ..> org.josemalucero.dominio.cuenta.Transferible
org.josemalucero.dominio.operacion.OperacionTransferencia --|> org.josemalucero.dominio.operacion.Registrable
org.josemalucero.dominio.operacion.OperacionTransferencia --|> org.josemalucero.dominio.operacion.Reversible
org.josemalucero.dominio.operacion.OperacionTransferencia --|> org.josemalucero.dominio.operacion.Validable
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaDestino ..> java.lang.Override
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaDestino ..> java.math.BigDecimal
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaDestino ..> java.math.RoundingMode
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaDestino ..> org.josemalucero.dominio.cuenta.CuentaRegular
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaDestino ..> org.josemalucero.dominio.moneda.ConversorMoneda
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaDestino ..> org.josemalucero.dominio.moneda.MonedaConvertible
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaDestino --|> org.josemalucero.dominio.operacion.OperacionTransferencia
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaOrigen ..> java.lang.Override
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaOrigen ..> java.math.BigDecimal
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaOrigen ..> java.math.RoundingMode
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaOrigen ..> org.josemalucero.dominio.cuenta.CuentaRegular
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaOrigen ..> org.josemalucero.dominio.moneda.ConversorMoneda
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaOrigen ..> org.josemalucero.dominio.moneda.MonedaConvertible
org.josemalucero.dominio.operacion.OperacionTransferenciaMonedaOrigen --|> org.josemalucero.dominio.operacion.OperacionTransferencia
org.josemalucero.dominio.operacion.RegistroOperacion ..> java.lang.Override
org.josemalucero.dominio.operacion.RegistroOperacion ..> java.math.BigDecimal
org.josemalucero.dominio.operacion.RegistroOperacion ..> java.time.LocalDateTime
org.josemalucero.dominio.usuario.ContextoUsuario ..> org.josemalucero.dominio.estados.EstadoEntrada
org.josemalucero.dominio.usuario.ContextoUsuario ..> org.josemalucero.dominio.estados.EstadoLogin
org.josemalucero.dominio.usuario.ContextoUsuario ..> org.josemalucero.dominio.estados.EstadoUsuario
org.josemalucero.dominio.usuario.ContextoUsuario ..> org.josemalucero.servicio.InputProvider
org.josemalucero.dominio.usuario.Usuario ..> org.josemalucero.dominio.cuenta.CuentaRegular
org.josemalucero.dominio.usuario.Usuario ..> org.josemalucero.dominio.moneda.MonedaConvertible
org.josemalucero.dominio.usuario.Usuario ..> org.josemalucero.servicio.RespositorioCuentas
org.josemalucero.servicio.BCryptPasswordEncoderService ..> java.lang.Override
org.josemalucero.servicio.BCryptPasswordEncoderService ..> org.mindrot.jbcrypt.BCrypt
org.josemalucero.servicio.BCryptPasswordEncoderService --|> org.josemalucero.servicio.PasswordEncoder
org.josemalucero.servicio.ConsoleInputProvider ..> java.lang.Override
org.josemalucero.servicio.ConsoleInputProvider ..> java.util.Scanner
org.josemalucero.servicio.ConsoleInputProvider --|> org.josemalucero.servicio.InputProvider
org.josemalucero.servicio.FormateadorDeRegistroAImprimir ..> org.josemalucero.dominio.operacion.RegistroOperacion
org.josemalucero.servicio.RepositorioMonedas ..> java.math.BigDecimal
org.josemalucero.servicio.RepositorioMonedas ..> java.util.ArrayList
org.josemalucero.servicio.RepositorioMonedas ..> java.util.Arrays
org.josemalucero.servicio.RepositorioMonedas ..> org.josemalucero.dominio.moneda.Moneda
org.josemalucero.servicio.RepositorioMonedas ..> org.josemalucero.dominio.moneda.MonedaConvertible
org.josemalucero.servicio.RepositorioMonedas ..> org.josemalucero.dominio.usuario.Usuario
org.josemalucero.servicio.RepositorioUsuarios ..> java.math.BigDecimal
org.josemalucero.servicio.RepositorioUsuarios ..> java.util.ArrayList
org.josemalucero.servicio.RepositorioUsuarios ..> java.util.Optional
org.josemalucero.servicio.RepositorioUsuarios ..> org.josemalucero.dominio.moneda.MonedaConvertible
org.josemalucero.servicio.RepositorioUsuarios ..> org.josemalucero.dominio.operacion.RegistroOperacion
org.josemalucero.servicio.RepositorioUsuarios ..> org.josemalucero.dominio.usuario.Usuario
org.josemalucero.servicio.RespositorioCuentas ..> java.util.ArrayList
org.josemalucero.servicio.RespositorioCuentas ..> java.util.Random
org.josemalucero.servicio.RespositorioCuentas ..> org.josemalucero.dominio.cuenta.Cuenta
org.josemalucero.servicio.RespositorioCuentas ..> org.josemalucero.dominio.cuenta.CuentaRegular
org.josemalucero.dominio.cuenta.Consultable ..> java.math.BigDecimal
org.josemalucero.dominio.cuenta.Depositable ..> java.math.BigDecimal
org.josemalucero.dominio.cuenta.Retirable ..> java.math.BigDecimal
org.josemalucero.dominio.cuenta.Transferible ..> java.math.BigDecimal
org.josemalucero.dominio.estados.EstadoUsuario ..> org.josemalucero.dominio.usuario.ContextoUsuario
org.josemalucero.dominio.operacion.Registrable ..> org.josemalucero.dominio.cuenta.CuentaRegular
@enduml